### ISSUE TITLE
[개발] 메인 페이지(전체 게시판)

### ISSUE THREAD

**Issue by HyoeunYoo** [Gachon-P-project/Web#10]
## 메인 페이지(전체 게시판)
> 로그인 후 메인 페이지에는 전체 게시판 리스트를 보여준다.
수업 게시판은 현재 수강 중인 수업 목록을 보여주고, 나머지 게시판은 최근 게시물 목록을 보여준다.

## 참여자
- 유효은
- 김진영

## 작업 내용
- 유효은
    - 전체 게시판 리스트 제작 - 웹, 모바일 버전 따로
    - 게시물 연결
    - 게시물 없는 경우

- 김진영
    - 게시판 별 게시물, 수업 조회

## 진행 상황
- [x] 전체 게시판 리스트 제작
- [x] 게시물 연결
- [x] 게시물 없는 경우
- [ ] 학과 게시물 조회 (최근 4개) #4 
- [ ] 수강 중인 수업 전체 조회 #4 
- [ ] 자유 게시물 조회 (최근 4개) #4  
- [ ] hot 게시물 조회 (5개) #4
