### ISSUE TITLE
[1월 18일~ 1월 24일] 유효은 TODO

### ISSUE THREAD

**Issue by HyoeunYoo** [Gachon-P-project/Web#23]
## 주요 내용
- [x] 게시판 breadcrumb -> pageheader로 교체
- [x] 게시물 검색 페이지 완료 #14 #25 
- [x] 공지사항 페이지 제작 #16 

## 상세 내용
1. 게시판 breadcrumb -> pageheader로 교체

2. 게시물 검색 페이지 완료
    - 게시물 없는 경우
    - 검색 결과 선택 후 뒤로가기 하면 결과 초기화 되는 문제 해결 #24 
 
3. 공지사항 페이지 제작
    - 공지사항 목록 제작
    - 상세 공지사항 내용 제작
